name: Deploy Hugo Site to AWS

on:
  push:
    branches: [ main ]          # Triggers on push to main
  workflow_dispatch:            # Allows manual trigger from GitHub UI

permissions:
  contents: read
  id-token: write               # Needed for OIDC authentication

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive     # Important if your theme is a Git submodule

      - name: Setup Hugo
        run: |
          HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep tag_name | cut -d '"' -f 4 | sed 's/v//')
          wget -O hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
          tar -xzf hugo.tar.gz
          sudo mv hugo /usr/local/bin/

      - name: Build site
        run: hugo --minify          # Generates the /public folder

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::669012865819:role/github-actions-hugo-deploy
          aws-region: us-east-1   # e.g., us-east-1

      - name: Deploy to S3 and invalidate CloudFront
        run: |
          aws s3 sync public/ s3://my-site-architectn --delete
          aws cloudfront create-invalidation --distribution-id E2255H14ASB2W1 --paths "/*"
